/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import Controlador.RegistroControlador;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author ms_ma
 */
public class VentanaRegistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistro.class.getName());
    private RegistroControlador registroControlador;
    /**
     * Creates new form VentanaInicioSesion
     */
    public VentanaRegistro() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); PARA QUE ESTÉ MAXIMIZADA
        panelScroll.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelRellenoIzq = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelRegistrarse = new javax.swing.JLabel();
        panelNombre = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        panelEmail = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        labelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        panelDireccion = new javax.swing.JPanel();
        labelDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        panelTelefono = new javax.swing.JPanel();
        labelTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnRegistrarse = new javax.swing.JButton();
        panelBoton = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        panelRellenoDer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(600, 500));

        panelScroll.setMaximumSize(new java.awt.Dimension(600, 800));
        panelScroll.setPreferredSize(new java.awt.Dimension(600, 1200));
        panelScroll.setViewportView(panelPrincipal);

        panelPrincipal.setMaximumSize(new java.awt.Dimension(800, 2147483647));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(400, 300));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelRellenoIzq.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoIzq.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoIzqLayout = new javax.swing.GroupLayout(panelRellenoIzq);
        panelRellenoIzq.setLayout(panelRellenoIzqLayout);
        panelRellenoIzqLayout.setHorizontalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        panelRellenoIzqLayout.setVerticalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoIzq, java.awt.BorderLayout.LINE_START);

        panelCentro.setMinimumSize(new java.awt.Dimension(400, 300));
        panelCentro.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCentro.setLayout(new java.awt.GridLayout(8, 1, 0, 35));

        labelRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRegistrarse.setText("Registrarse");
        labelRegistrarse.setToolTipText("");
        labelRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(labelRegistrarse);

        panelCentro.add(panelTitulo);

        panelNombre.setLayout(new java.awt.GridLayout(2, 1));

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombre.setText("Nombre o Apellido de la familia");
        labelNombre.setToolTipText("");
        panelNombre.add(labelNombre);
        panelNombre.add(txtNombre);

        panelCentro.add(panelNombre);

        panelEmail.setLayout(new java.awt.GridLayout(2, 1));

        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmail.setText("Correo Electrónico");
        labelEmail.setToolTipText("");
        panelEmail.add(labelEmail);
        panelEmail.add(txtEmail);

        panelCentro.add(panelEmail);

        panelPassword.setLayout(new java.awt.GridLayout(2, 1));

        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPassword.setText("Contraseña");
        labelPassword.setToolTipText("");
        panelPassword.add(labelPassword);
        panelPassword.add(txtPassword);

        panelCentro.add(panelPassword);

        panelDireccion.setLayout(new java.awt.GridLayout(2, 1));

        labelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDireccion.setText("Dirección");
        labelDireccion.setToolTipText("");
        panelDireccion.add(labelDireccion);
        panelDireccion.add(txtDireccion);

        panelCentro.add(panelDireccion);

        panelTelefono.setLayout(new java.awt.GridLayout(2, 1));

        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTelefono.setText("Teléfono / Celular");
        labelTelefono.setToolTipText("");
        panelTelefono.add(labelTelefono);
        panelTelefono.add(txtTelefono);

        panelCentro.add(panelTelefono);

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrarse.setText("Crear Cuenta");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        panelBotones.add(btnRegistrarse);

        panelCentro.add(panelBotones);

        panelBoton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnVolver.setText("Volver");
        panelBoton.add(btnVolver);

        panelCentro.add(panelBoton);

        panelPrincipal.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelRellenoDer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoDer.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoDerLayout = new javax.swing.GroupLayout(panelRellenoDer);
        panelRellenoDer.setLayout(panelRellenoDerLayout);
        panelRellenoDerLayout.setHorizontalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRellenoDerLayout.setVerticalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoDer, java.awt.BorderLayout.EAST);

        panelScroll.setViewportView(panelPrincipal);

        getContentPane().add(panelScroll, java.awt.BorderLayout.NORTH);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        registroControlador.procesarRegistrarse(); // llama al controlador
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRegistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegistrarse;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDireccion;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRellenoDer;
    private javax.swing.JPanel panelRellenoIzq;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JPanel panelTelefono;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
    public void setRegistroControlador(RegistroControlador ctrl) {
        this.registroControlador = ctrl;
    }
   
    public String getEmail(){
        return txtEmail.getText();
    }
    public String getPassword(){
        return new String(txtPassword.getPassword());
    }

    public static Logger getLogger() {
        return logger;
    }

    public RegistroControlador getRegistroControlador() {
        return registroControlador;
    }

    public JButton getBtnRegistrarse() {
        return btnRegistrarse;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public JLabel getLabelDireccion() {
        return labelDireccion;
    }

    public JLabel getLabelEmail() {
        return labelEmail;
    }

    public JLabel getLabelNombre() {
        return labelNombre;
    }

    public JLabel getLabelPassword() {
        return labelPassword;
    }

    public JLabel getLabelRegistrarse() {
        return labelRegistrarse;
    }

    public JLabel getLabelTelefono() {
        return labelTelefono;
    }

    public JPanel getPanelBoton() {
        return panelBoton;
    }

    public JPanel getPanelBotones() {
        return panelBotones;
    }

    public JPanel getPanelCentro() {
        return panelCentro;
    }

    public JPanel getPanelDireccion() {
        return panelDireccion;
    }

    public JPanel getPanelEmail() {
        return panelEmail;
    }

    public JPanel getPanelNombre() {
        return panelNombre;
    }

    public JPanel getPanelPassword() {
        return panelPassword;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public JPanel getPanelRellenoDer() {
        return panelRellenoDer;
    }

    public JPanel getPanelRellenoIzq() {
        return panelRellenoIzq;
    }

    public JScrollPane getPanelScroll() {
        return panelScroll;
    }

    public JPanel getPanelTelefono() {
        return panelTelefono;
    }

    public JPanel getPanelTitulo() {
        return panelTitulo;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }
    
    
}
