/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JFrame;

/**
 *
 * @author ms_ma
 */
public class VentanaInicioSesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName());

    /**
     * Creates new form VentanaInicioSesion
     */
    public VentanaInicioSesion() {
        initComponents();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); PARA QUE ESTÉ MAXIMIZADA
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTipoUsuario = new javax.swing.JPanel();
        btnFamiliaAdoptante = new javax.swing.JButton();
        btnVoluntario = new javax.swing.JButton();
        btnVeterinario = new javax.swing.JButton();
        btnAdministrador = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        panelRellenoIzq = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();
        panelEmail = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        panelPassword = new javax.swing.JPanel();
        labelPassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        panelBotones = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        panelBoton = new javax.swing.JPanel();
        btnRestablecerPass = new javax.swing.JButton();
        panelRellenoDer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));

        panelTipoUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        panelTipoUsuario.setLayout(new java.awt.GridLayout(1, 3, 60, 25));

        btnFamiliaAdoptante.setText("Familia Adoptante");
        panelTipoUsuario.add(btnFamiliaAdoptante);

        btnVoluntario.setText("Voluntario");
        panelTipoUsuario.add(btnVoluntario);

        btnVeterinario.setText("Veterinario");
        panelTipoUsuario.add(btnVeterinario);

        btnAdministrador.setText("Administrador");
        panelTipoUsuario.add(btnAdministrador);

        getContentPane().add(panelTipoUsuario, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelRellenoIzq.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));

        javax.swing.GroupLayout panelRellenoIzqLayout = new javax.swing.GroupLayout(panelRellenoIzq);
        panelRellenoIzq.setLayout(panelRellenoIzqLayout);
        panelRellenoIzqLayout.setHorizontalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRellenoIzqLayout.setVerticalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoIzq, java.awt.BorderLayout.LINE_START);

        panelCentro.setLayout(new java.awt.GridLayout(4, 1, 0, 35));

        panelEmail.setLayout(new java.awt.GridLayout(2, 1));

        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmail.setText("Correo Electrónico");
        labelEmail.setToolTipText("");
        panelEmail.add(labelEmail);
        panelEmail.add(emailField);

        panelCentro.add(panelEmail);

        panelPassword.setLayout(new java.awt.GridLayout(2, 1));

        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPassword.setText("Contraseña");
        labelPassword.setToolTipText("");
        panelPassword.add(labelPassword);
        labelPassword.getAccessibleContext().setAccessibleName("Contraseña");

        panelPassword.add(jPasswordField1);

        panelCentro.add(panelPassword);

        panelBotones.setLayout(new java.awt.GridLayout(1, 0, 100, 0));

        btnIngresar.setText("Ingresar");
        panelBotones.add(btnIngresar);

        btnRegistrarse.setText("Crear Cuenta");
        panelBotones.add(btnRegistrarse);

        panelCentro.add(panelBotones);

        btnRestablecerPass.setText("Olvidé mi contraseña");
        panelBoton.add(btnRestablecerPass);

        panelCentro.add(panelBoton);

        panelPrincipal.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelRellenoDer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));

        javax.swing.GroupLayout panelRellenoDerLayout = new javax.swing.GroupLayout(panelRellenoDer);
        panelRellenoDer.setLayout(panelRellenoDerLayout);
        panelRellenoDerLayout.setHorizontalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRellenoDerLayout.setVerticalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoDer, java.awt.BorderLayout.EAST);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnFamiliaAdoptante;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnRestablecerPass;
    private javax.swing.JButton btnVeterinario;
    private javax.swing.JButton btnVoluntario;
    private javax.swing.JTextField emailField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRellenoDer;
    private javax.swing.JPanel panelRellenoIzq;
    private javax.swing.JPanel panelTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
