/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.gato;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.TipoRegistroMedico;

/**
 *
 * @author ms_ma
 */
public class VentanaAgregarRegistroMedico extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAgregarRegistroMedico.class.getName());

    /**
     * Creates new form VentanaAgregarRegistroMedico
     */
    public VentanaAgregarRegistroMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelTipo = new javax.swing.JPanel();
        lblTipoTarea = new javax.swing.JLabel();
        ComboTipo = new javax.swing.JComboBox<>();
        panelDescripcion = new javax.swing.JPanel();
        lblDescipcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        panelArchivo = new javax.swing.JPanel();
        lblArchivo = new javax.swing.JLabel();
        txtArchivoEstudio = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));

        panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        panelCentro.setMinimumSize(new java.awt.Dimension(400, 300));
        panelCentro.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCentro.setLayout(new java.awt.GridLayout(5, 1, 5, 35));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitulo.setText("Agregar Registro");
        lblTitulo.setToolTipText("");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(lblTitulo);

        panelCentro.add(panelTitulo);

        panelTipo.setLayout(new java.awt.GridLayout(2, 1));

        lblTipoTarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoTarea.setText("Tipo de registro");
        lblTipoTarea.setToolTipText("");
        panelTipo.add(lblTipoTarea);

        panelTipo.add(ComboTipo);

        panelCentro.add(panelTipo);

        panelDescripcion.setLayout(new java.awt.GridLayout(2, 1));

        lblDescipcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescipcion.setText("Descripcion");
        lblDescipcion.setToolTipText("");
        panelDescripcion.add(lblDescipcion);

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        panelDescripcion.add(txtDescripcion);

        panelCentro.add(panelDescripcion);

        panelArchivo.setLayout(new java.awt.GridLayout(2, 1));

        lblArchivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblArchivo.setText("Archivo");
        lblArchivo.setToolTipText("");
        panelArchivo.add(lblArchivo);

        txtArchivoEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArchivoEstudioActionPerformed(evt);
            }
        });
        panelArchivo.add(txtArchivoEstudio);

        panelCentro.add(panelArchivo);

        panelBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBoton.add(btnGuardar);

        panelCentro.add(panelBoton);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtArchivoEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArchivoEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArchivoEstudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaAgregarRegistroMedico dialog = new VentanaAgregarRegistroMedico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<TipoRegistroMedico> ComboTipo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblDescipcion;
    private javax.swing.JLabel lblTipoTarea;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelArchivo;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelDescripcion;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextField txtArchivoEstudio;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

    public JComboBox<TipoRegistroMedico> getComboTipo() {
        return ComboTipo;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JTextField getTxtArchivoEstudio() {
        return txtArchivoEstudio;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    
}
