/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.gato;

/**
 *
 * @author ms_ma
 */
public class VentanaRegistrarGato extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistrarGato.class.getName());

    /**
     * Creates new form VentanaRegistrarGato
     */
    public VentanaRegistrarGato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelRellenoIzq = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelRegistrarse = new javax.swing.JLabel();
        panelNombre = new javax.swing.JPanel();
        lblTipoTarea = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        panelColor = new javax.swing.JPanel();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        panelUbicacion = new javax.swing.JPanel();
        lblZona = new javax.swing.JLabel();
        panelSeleccionarUbicacion = new javax.swing.JPanel();
        comboZona = new javax.swing.JComboBox<>();
        texto = new javax.swing.JLabel();
        btnAgregarUbicacion = new javax.swing.JButton();
        panelCaracteristicas = new javax.swing.JPanel();
        lblCaracteristicas = new javax.swing.JLabel();
        txtCaracteristicas = new javax.swing.JTextField();
        panelEstadoSalud = new javax.swing.JPanel();
        lblEstadoSalud = new javax.swing.JLabel();
        comboEstadoSalud = new javax.swing.JComboBox<>();
        panelCaracteristicas1 = new javax.swing.JPanel();
        lblCaracteristicas1 = new javax.swing.JLabel();
        txtCaracteristicas1 = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        panelRellenoDer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setMaximumSize(new java.awt.Dimension(10000, 2147483647));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(900, 800));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(900, 800));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelRellenoIzq.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoIzq.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoIzqLayout = new javax.swing.GroupLayout(panelRellenoIzq);
        panelRellenoIzq.setLayout(panelRellenoIzqLayout);
        panelRellenoIzqLayout.setHorizontalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        panelRellenoIzqLayout.setVerticalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoIzq, java.awt.BorderLayout.LINE_START);

        panelCentro.setMinimumSize(new java.awt.Dimension(400, 300));
        panelCentro.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCentro.setLayout(new java.awt.GridLayout(8, 1, 0, 35));

        labelRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRegistrarse.setText("Registrar Gato");
        labelRegistrarse.setToolTipText("");
        labelRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(labelRegistrarse);

        panelCentro.add(panelTitulo);

        panelNombre.setLayout(new java.awt.GridLayout(2, 1));

        lblTipoTarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoTarea.setText("Nombre del Gato");
        lblTipoTarea.setToolTipText("");
        panelNombre.add(lblTipoTarea);
        panelNombre.add(txtNombre);

        panelCentro.add(panelNombre);

        panelColor.setLayout(new java.awt.GridLayout(2, 1));

        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblColor.setText("Color");
        lblColor.setToolTipText("");
        panelColor.add(lblColor);
        panelColor.add(txtColor);

        panelCentro.add(panelColor);

        panelUbicacion.setLayout(new java.awt.GridLayout(2, 1));

        lblZona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZona.setText("Zona");
        lblZona.setToolTipText("");
        panelUbicacion.add(lblZona);

        panelSeleccionarUbicacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 0));

        comboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelSeleccionarUbicacion.add(comboZona);

        texto.setText("¿La ubicación no está registrada?");
        texto.setMaximumSize(new java.awt.Dimension(200, 16));
        texto.setMinimumSize(new java.awt.Dimension(200, 16));
        texto.setPreferredSize(new java.awt.Dimension(200, 16));
        panelSeleccionarUbicacion.add(texto);

        btnAgregarUbicacion.setText("Agregar Ubicación");
        panelSeleccionarUbicacion.add(btnAgregarUbicacion);

        panelUbicacion.add(panelSeleccionarUbicacion);

        panelCentro.add(panelUbicacion);

        panelCaracteristicas.setLayout(new java.awt.GridLayout(2, 1));

        lblCaracteristicas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCaracteristicas.setText("Caracteristicas / Observaciones");
        lblCaracteristicas.setToolTipText("");
        panelCaracteristicas.add(lblCaracteristicas);
        panelCaracteristicas.add(txtCaracteristicas);

        panelCentro.add(panelCaracteristicas);

        panelEstadoSalud.setLayout(new java.awt.GridLayout(2, 1));

        lblEstadoSalud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstadoSalud.setText("Estado de Salud");
        lblEstadoSalud.setToolTipText("");
        panelEstadoSalud.add(lblEstadoSalud);

        comboEstadoSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelEstadoSalud.add(comboEstadoSalud);

        panelCentro.add(panelEstadoSalud);

        panelCaracteristicas1.setLayout(new java.awt.GridLayout(2, 1));

        lblCaracteristicas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCaracteristicas1.setText("Agregar Foto");
        lblCaracteristicas1.setToolTipText("");
        panelCaracteristicas1.add(lblCaracteristicas1);
        panelCaracteristicas1.add(txtCaracteristicas1);

        panelCentro.add(panelCaracteristicas1);

        panelBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBoton.add(btnGuardar);

        panelCentro.add(panelBoton);

        panelPrincipal.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelRellenoDer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoDer.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoDerLayout = new javax.swing.GroupLayout(panelRellenoDer);
        panelRellenoDer.setLayout(panelRellenoDerLayout);
        panelRellenoDerLayout.setHorizontalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRellenoDerLayout.setVerticalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoDer, java.awt.BorderLayout.EAST);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaRegistrarGato dialog = new VentanaRegistrarGato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarUbicacion;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboEstadoSalud;
    private javax.swing.JComboBox<String> comboZona;
    private javax.swing.JLabel labelRegistrarse;
    private javax.swing.JLabel lblCaracteristicas;
    private javax.swing.JLabel lblCaracteristicas1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEstadoSalud;
    private javax.swing.JLabel lblTipoTarea;
    private javax.swing.JLabel lblZona;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCaracteristicas;
    private javax.swing.JPanel panelCaracteristicas1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelEstadoSalud;
    private javax.swing.JPanel panelNombre;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRellenoDer;
    private javax.swing.JPanel panelRellenoIzq;
    private javax.swing.JPanel panelSeleccionarUbicacion;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelUbicacion;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtCaracteristicas;
    private javax.swing.JTextField txtCaracteristicas1;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
    
    

}
