/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.gato;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import modelo.TipoTarea;
import modelo.Zona;

/**
 *
 * @author ms_ma
 */
public class VentanaRegistrarTarea extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistrarTarea.class.getName());

    /**
     * Creates new form VentanaRegistrarTarea
     */
    public VentanaRegistrarTarea(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelRellenoIzq = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelRegistrarse = new javax.swing.JLabel();
        panelTipoTarea = new javax.swing.JPanel();
        lblTipoTarea = new javax.swing.JLabel();
        comboTipoTarea = new javax.swing.JComboBox<>();
        panelEmail = new javax.swing.JPanel();
        labelVoluntario = new javax.swing.JLabel();
        lblNombreVoluntario = new javax.swing.JLabel();
        panelUbicacion = new javax.swing.JPanel();
        lblZona = new javax.swing.JLabel();
        panelSeleccionarUbicacion = new javax.swing.JPanel();
        comboZona = new javax.swing.JComboBox<>();
        texto = new javax.swing.JLabel();
        btnAgregarZona = new javax.swing.JButton();
        panelObservaciones = new javax.swing.JPanel();
        lblObservaciones = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        panelRellenoDer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);

        panelPrincipal.setMaximumSize(new java.awt.Dimension(800, 2147483647));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(800, 600));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelRellenoIzq.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoIzq.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoIzqLayout = new javax.swing.GroupLayout(panelRellenoIzq);
        panelRellenoIzq.setLayout(panelRellenoIzqLayout);
        panelRellenoIzqLayout.setHorizontalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        panelRellenoIzqLayout.setVerticalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoIzq, java.awt.BorderLayout.LINE_START);

        panelCentro.setMinimumSize(new java.awt.Dimension(400, 300));
        panelCentro.setPreferredSize(new java.awt.Dimension(400, 300));
        panelCentro.setLayout(new java.awt.GridLayout(7, 1, 0, 25));

        labelRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelRegistrarse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRegistrarse.setText("Registrar Tarea");
        labelRegistrarse.setToolTipText("");
        labelRegistrarse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelTitulo.add(labelRegistrarse);

        panelCentro.add(panelTitulo);

        panelTipoTarea.setLayout(new java.awt.GridLayout(2, 1));

        lblTipoTarea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoTarea.setText("Tipo de tarea");
        lblTipoTarea.setToolTipText("");
        panelTipoTarea.add(lblTipoTarea);

        comboTipoTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelTipoTarea.add(comboTipoTarea);

        panelCentro.add(panelTipoTarea);

        panelEmail.setLayout(new java.awt.GridLayout(2, 1));

        labelVoluntario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelVoluntario.setText("Voluntario");
        labelVoluntario.setToolTipText("");
        panelEmail.add(labelVoluntario);

        lblNombreVoluntario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreVoluntario.setText("Voluntario");
        lblNombreVoluntario.setToolTipText("");
        panelEmail.add(lblNombreVoluntario);

        panelCentro.add(panelEmail);

        panelUbicacion.setLayout(new java.awt.GridLayout(2, 1));

        lblZona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZona.setText("Zona");
        lblZona.setToolTipText("");
        panelUbicacion.add(lblZona);

        panelSeleccionarUbicacion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 0));

        comboZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelSeleccionarUbicacion.add(comboZona);

        texto.setText("¿La ubicación no está registrada?");
        texto.setMaximumSize(new java.awt.Dimension(200, 16));
        texto.setMinimumSize(new java.awt.Dimension(200, 16));
        texto.setPreferredSize(new java.awt.Dimension(200, 16));
        panelSeleccionarUbicacion.add(texto);

        btnAgregarZona.setText("Agregar Zona");
        panelSeleccionarUbicacion.add(btnAgregarZona);

        panelUbicacion.add(panelSeleccionarUbicacion);

        panelCentro.add(panelUbicacion);

        panelObservaciones.setLayout(new java.awt.GridLayout(2, 1));

        lblObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblObservaciones.setText("Observaciones");
        lblObservaciones.setToolTipText("");
        panelObservaciones.add(lblObservaciones);
        panelObservaciones.add(txtObservaciones);

        panelCentro.add(panelObservaciones);

        panelBoton.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 1, 1));

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panelBoton.add(btnGuardar);

        panelCentro.add(panelBoton);

        panelPrincipal.add(panelCentro, java.awt.BorderLayout.CENTER);

        panelRellenoDer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));
        panelRellenoDer.setPreferredSize(new java.awt.Dimension(100, 1193));

        javax.swing.GroupLayout panelRellenoDerLayout = new javax.swing.GroupLayout(panelRellenoDer);
        panelRellenoDer.setLayout(panelRellenoDerLayout);
        panelRellenoDerLayout.setHorizontalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRellenoDerLayout.setVerticalGroup(
            panelRellenoDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        panelPrincipal.add(panelRellenoDer, java.awt.BorderLayout.EAST);

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaRegistrarTarea dialog = new VentanaRegistrarTarea(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarZona;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboTipoTarea;
    private javax.swing.JComboBox<String> comboZona;
    private javax.swing.JLabel labelRegistrarse;
    private javax.swing.JLabel labelVoluntario;
    private javax.swing.JLabel lblNombreVoluntario;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTipoTarea;
    private javax.swing.JLabel lblZona;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelObservaciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRellenoDer;
    private javax.swing.JPanel panelRellenoIzq;
    private javax.swing.JPanel panelSeleccionarUbicacion;
    private javax.swing.JPanel panelTipoTarea;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelUbicacion;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void cargarTiposTarea(List<TipoTarea> tipos) {
        comboTipoTarea.removeAllItems();
        for (TipoTarea t : tipos) {
            comboTipoTarea.addItem(t.toString());
        }
    }
    
    public void cargarZona(List<Zona> zonas) {
        comboZona.removeAllItems();
        for (Zona z : zonas) {
            comboZona.addItem(z.getNombre());
        }
    }

    public JComboBox<String> getComboTipoTarea() {
        return comboTipoTarea;
    }

    public JComboBox<String> getComboZona() {
        return comboZona;
    }

    public JLabel getLblNombreVoluntario() {
        return lblNombreVoluntario;
    }

    public JTextField getTxtObservaciones() {
        return txtObservaciones;
    }

    public void setLblNombreVoluntario(String text) {
        this.lblNombreVoluntario.setText(text);
    }

    public JButton getBtnAgregarZona() {
        return btnAgregarZona;
    }
    
}
