/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.familia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ms_ma
 */
public class PanelPrincipalFamiliaAdoptante extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalFamiliaAdoptante
     */
    public PanelPrincipalFamiliaAdoptante() {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorth = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGatos = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 1, 1));

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido");
        panelNorth.add(lblBienvenido);

        add(panelNorth, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(panelGatos);

        panelGatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        panelGatos.setMinimumSize(new java.awt.Dimension(500, 600));
        panelGatos.setPreferredSize(null);
        panelGatos.setLayout(new java.awt.GridLayout(0, 3, 20, 20));
        jScrollPane1.setViewportView(panelGatos);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JPanel panelGatos;
    private javax.swing.JPanel panelNorth;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getPanelGatos(){
        return panelGatos;
    }

    public JLabel getLblBienvenido() {
        return lblBienvenido;
    }

    
    
    public void setLblBienvenido(JLabel lblBienvenido) {
        this.lblBienvenido = lblBienvenido;
    }

    
}
