/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.familia;

import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import modelo.Gato;

/**
 *
 * @author ms_ma
 */
public class PanelGatoCard extends javax.swing.JPanel {

    /**
     * Creates new form PanelGatoCard
     */
    public PanelGatoCard(Gato gato) {
        initComponents();
        lblNombre.setText(gato.getNombre());
        setPreferredSize(new Dimension(400, 500)); // Ancho x Alto

        // Carga dinámica de la imagen desde resources
        URL url = getClass().getResource("/Recursos/Imagenes/" + gato.getFoto());
        if (url != null) {
            lblFoto.setIcon(new ImageIcon(url));
        } else {
            // Imagen por defecto si no se encuentra
            lblFoto.setIcon(new ImageIcon(getClass().getResource("/Recursos/Imagenes/default.jpg")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnVerGato = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 1));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setMaximumSize(new java.awt.Dimension(226, 198));
        add(lblFoto);

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        add(lblNombre);

        btnVerGato.setText("Ver gato");
        add(btnVerGato);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerGato;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
