/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.familia;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ms_ma
 */
public class PanelPrincipalFamiliaAdoptante extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalFamiliaAdoptante
     */
    public PanelPrincipalFamiliaAdoptante() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorth = new javax.swing.JPanel();
        panelRellenoIzq = new javax.swing.JPanel();
        panelRellenoDerecha = new javax.swing.JPanel();
        panelGatos = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 1, 1));
        add(panelNorth, java.awt.BorderLayout.NORTH);

        panelRellenoIzq.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));

        javax.swing.GroupLayout panelRellenoIzqLayout = new javax.swing.GroupLayout(panelRellenoIzq);
        panelRellenoIzq.setLayout(panelRellenoIzqLayout);
        panelRellenoIzqLayout.setHorizontalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRellenoIzqLayout.setVerticalGroup(
            panelRellenoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(panelRellenoIzq, java.awt.BorderLayout.LINE_START);

        panelRellenoDerecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 50, 1, 1));

        javax.swing.GroupLayout panelRellenoDerechaLayout = new javax.swing.GroupLayout(panelRellenoDerecha);
        panelRellenoDerecha.setLayout(panelRellenoDerechaLayout);
        panelRellenoDerechaLayout.setHorizontalGroup(
            panelRellenoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelRellenoDerechaLayout.setVerticalGroup(
            panelRellenoDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(panelRellenoDerecha, java.awt.BorderLayout.EAST);

        panelGatos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        panelGatos.setMinimumSize(new java.awt.Dimension(500, 600));
        panelGatos.setPreferredSize(new java.awt.Dimension(500, 600));
        add(panelGatos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelGatos;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelRellenoDerecha;
    private javax.swing.JPanel panelRellenoIzq;
    // End of variables declaration//GEN-END:variables
    
    public JPanel getPanelGatos(){
        return panelGatos;
    }

}
