/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.familia;

import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Gato;

/**
 *
 * @author ms_ma
 */
public class PanelGatoCard extends javax.swing.JPanel {

    /**
     * Creates new form PanelGatoCard
     */
    public PanelGatoCard(Gato gato) {
        initComponents();

        lblNombre.setText(gato.getNombre());

        byte[] bytesFoto = gato.getFoto();
        ImageIcon icon;

        if (bytesFoto != null && bytesFoto.length > 0) {
            Image img = new ImageIcon(bytesFoto).getImage()
                       .getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            icon = new ImageIcon(img);
        } else {
            icon = new ImageIcon(getClass().getResource("/Recursos/Imagenes/default.jpg"));
        }

        lblFoto.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        btnVerGato = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setToolTipText("");
        lblFoto.setFocusCycleRoot(true);
        lblFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFoto.setMaximumSize(new java.awt.Dimension(400, 250));
        lblFoto.setMinimumSize(new java.awt.Dimension(200, 200));
        lblFoto.setPreferredSize(new java.awt.Dimension(200, 200));
        add(lblFoto, java.awt.BorderLayout.CENTER);

        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 0, 15));
        panel.setAlignmentX(0.5F);

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setAlignmentX(0.5F);
        panel.add(lblNombre);

        btnVerGato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerGato.setText("Ver gato");
        btnVerGato.setAlignmentX(0.5F);
        btnVerGato.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnVerGato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerGato.setMaximumSize(new java.awt.Dimension(100, 70));
        btnVerGato.setMinimumSize(new java.awt.Dimension(50, 10));
        btnVerGato.setPreferredSize(new java.awt.Dimension(100, 70));
        btnVerGato.setVerifyInputWhenFocusTarget(false);
        panel.add(btnVerGato);

        add(panel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerGato;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
