/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.administrador;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;
import modelo.Zona;


/**
 *
 * @author ms_ma
 */
public class PanelPrincipalAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalAdministrador
     */
    public PanelPrincipalAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNorth = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        panelCentro = new javax.swing.JPanel();
        panelUsuarios = new javax.swing.JPanel();
        panelListas = new javax.swing.JPanel();
        panelFamilias = new javax.swing.JPanel();
        panelTituloBuscar = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarFamilia = new javax.swing.JTextField();
        btnBuscarFamilia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFamilias = new javax.swing.JList<>();
        panelVoluntarios = new javax.swing.JPanel();
        panelTituloBuscar1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarVoluntario = new javax.swing.JTextField();
        btnBuscarVoluntario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVoluntarios = new javax.swing.JList<>();
        panelVeterinarios = new javax.swing.JPanel();
        panelTituloBuscar2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarVeterinario = new javax.swing.JTextField();
        btnBuscarVeterinario = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaVeterinarios = new javax.swing.JList<>();
        panelBotones = new javax.swing.JPanel();
        btnEliminarUsuario = new javax.swing.JButton();
        btnRegistrarVoluntario = new javax.swing.JButton();
        btnRegistrarVeterinario = new javax.swing.JButton();
        panelReportes = new javax.swing.JPanel();
        panelGatos = new javax.swing.JPanel();
        panelReportesCentro = new javax.swing.JPanel();
        panelFiltros1 = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboTipoReporte = new javax.swing.JComboBox<>();
        comboZona = new javax.swing.JComboBox<>();
        btnAplicar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaGatos = new javax.swing.JList<>();
        panelBotones1 = new javax.swing.JPanel();
        btnZonas = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setLayout(new java.awt.BorderLayout());

        panelNorth.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 1, 30, 1));

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBienvenido.setText("Bienvenido");
        lblBienvenido.setToolTipText("");
        panelNorth.add(lblBienvenido);

        add(panelNorth, java.awt.BorderLayout.NORTH);

        panelCentro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        panelCentro.setLayout(new java.awt.GridLayout(1, 2, 50, 0));

        panelUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        java.awt.GridBagLayout panelUsuariosLayout = new java.awt.GridBagLayout();
        panelUsuariosLayout.columnWeights = new double[] {1.0};
        panelUsuariosLayout.rowWeights = new double[] {1.0, 0.0};
        panelUsuarios.setLayout(panelUsuariosLayout);

        panelListas.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        panelFamilias.setLayout(new java.awt.BorderLayout(0, 10));

        panelTituloBuscar.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        lblTitulo.setText("Familias Adoptantes");
        lblTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        panelTituloBuscar.add(lblTitulo);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("buscar por apellido");
        panelTituloBuscar.add(jLabel3);
        panelTituloBuscar.add(txtBuscarFamilia);

        btnBuscarFamilia.setText("Buscar");
        btnBuscarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFamiliaActionPerformed(evt);
            }
        });
        panelTituloBuscar.add(btnBuscarFamilia);

        panelFamilias.add(panelTituloBuscar, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(listaFamilias);

        panelFamilias.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelListas.add(panelFamilias);

        panelVoluntarios.setLayout(new java.awt.BorderLayout());

        panelTituloBuscar1.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        lblTitulo1.setText("Voluntarios");
        lblTitulo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        panelTituloBuscar1.add(lblTitulo1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("buscar por nombre");
        panelTituloBuscar1.add(jLabel4);
        panelTituloBuscar1.add(txtBuscarVoluntario);

        btnBuscarVoluntario.setText("Buscar");
        btnBuscarVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVoluntarioActionPerformed(evt);
            }
        });
        panelTituloBuscar1.add(btnBuscarVoluntario);

        panelVoluntarios.add(panelTituloBuscar1, java.awt.BorderLayout.NORTH);

        jScrollPane2.setViewportView(listaVoluntarios);

        panelVoluntarios.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelListas.add(panelVoluntarios);

        panelVeterinarios.setLayout(new java.awt.BorderLayout());

        panelTituloBuscar2.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        lblTitulo2.setText("Veterinarios");
        lblTitulo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        panelTituloBuscar2.add(lblTitulo2);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("buscar por nombre");
        panelTituloBuscar2.add(jLabel5);
        panelTituloBuscar2.add(txtBuscarVeterinario);

        btnBuscarVeterinario.setText("Buscar");
        btnBuscarVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVeterinarioActionPerformed(evt);
            }
        });
        panelTituloBuscar2.add(btnBuscarVeterinario);

        panelVeterinarios.add(panelTituloBuscar2, java.awt.BorderLayout.NORTH);

        jScrollPane3.setViewportView(listaVeterinarios);

        panelVeterinarios.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelListas.add(panelVeterinarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelUsuarios.add(panelListas, gridBagConstraints);

        panelBotones.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnEliminarUsuario.setText("Eliminar usuario");
        panelBotones.add(btnEliminarUsuario);

        btnRegistrarVoluntario.setText("Registrar Voluntario");
        panelBotones.add(btnRegistrarVoluntario);

        btnRegistrarVeterinario.setText("Registrar Veterinario");
        panelBotones.add(btnRegistrarVeterinario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelUsuarios.add(panelBotones, gridBagConstraints);

        panelCentro.add(panelUsuarios);

        panelReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        panelReportes.setLayout(new java.awt.GridBagLayout());

        panelGatos.setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        panelReportesCentro.setLayout(new java.awt.BorderLayout(0, 5));

        panelFiltros1.setLayout(new java.awt.GridLayout(1, 2, 3, 0));

        lblTitulo4.setText("Gatos");
        lblTitulo4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        panelFiltros1.add(lblTitulo4);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Tipo de reporte: ");
        panelFiltros1.add(jLabel2);

        panelFiltros1.add(comboTipoReporte);

        panelFiltros1.add(comboZona);

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        panelFiltros1.add(btnAplicar);

        panelReportesCentro.add(panelFiltros1, java.awt.BorderLayout.NORTH);

        jScrollPane4.setViewportView(listaGatos);

        panelReportesCentro.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelGatos.add(panelReportesCentro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelReportes.add(panelGatos, gridBagConstraints);

        panelBotones1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        btnZonas.setText("Gestionar Zonas");
        panelBotones1.add(btnZonas);

        btnReporte.setText("Generar Reporte");
        panelBotones1.add(btnReporte);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelReportes.add(panelBotones1, gridBagConstraints);

        panelCentro.add(panelReportes);

        add(panelCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnBuscarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarFamiliaActionPerformed

    private void btnBuscarVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVoluntarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarVoluntarioActionPerformed

    private void btnBuscarVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarVeterinarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnBuscarFamilia;
    private javax.swing.JButton btnBuscarVeterinario;
    private javax.swing.JButton btnBuscarVoluntario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnRegistrarVeterinario;
    private javax.swing.JButton btnRegistrarVoluntario;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnZonas;
    private javax.swing.JComboBox<String> comboTipoReporte;
    private javax.swing.JComboBox<Zona> comboZona;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JList<String> listaFamilias;
    private javax.swing.JList<String> listaGatos;
    private javax.swing.JList<String> listaVeterinarios;
    private javax.swing.JList<String> listaVoluntarios;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBotones1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelFamilias;
    private javax.swing.JPanel panelFiltros1;
    private javax.swing.JPanel panelGatos;
    private javax.swing.JPanel panelListas;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel panelReportesCentro;
    private javax.swing.JPanel panelTituloBuscar;
    private javax.swing.JPanel panelTituloBuscar1;
    private javax.swing.JPanel panelTituloBuscar2;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JPanel panelVeterinarios;
    private javax.swing.JPanel panelVoluntarios;
    private javax.swing.JTextField txtBuscarFamilia;
    private javax.swing.JTextField txtBuscarVeterinario;
    private javax.swing.JTextField txtBuscarVoluntario;
    // End of variables declaration//GEN-END:variables

    public void cargarListaGatos(List<String> items) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String s : items) model.addElement(s);
        listaGatos.setModel(model);
    }
    public void cargarListaFamilias(List<String> items) {
        DefaultListModel<String> m = new DefaultListModel<>();
        items.forEach(m::addElement);
        listaFamilias.setModel(m);
    }

    public void cargarListaVoluntarios(List<String> items) {
        DefaultListModel<String> m = new DefaultListModel<>();
        items.forEach(m::addElement);
        listaVoluntarios.setModel(m);
    }

    public void cargarListaVeterinarios(List<String> items) {
        DefaultListModel<String> m = new DefaultListModel<>();
        items.forEach(m::addElement);
        listaVeterinarios.setModel(m);
    }

    public JButton getBtnBuscarFamilia() {
        return btnBuscarFamilia;
    }

    public JButton getBtnBuscarVeterinario() {
        return btnBuscarVeterinario;
    }

    public JButton getBtnBuscarVoluntario() {
        return btnBuscarVoluntario;
    }

    public JButton getBtnRegistrarVeterinario() {
        return btnRegistrarVeterinario;
    }

    public JButton getBtnRegistrarVoluntario() {
        return btnRegistrarVoluntario;
    }

    public JTextField getTxtBuscarFamilia() {
        return txtBuscarFamilia;
    }

    public JTextField getTxtBuscarVeterinario() {
        return txtBuscarVeterinario;
    }

    public JTextField getTxtBuscarVoluntario() {
        return txtBuscarVoluntario;
    }

    public JList<String> getListaFamilias() {
        return listaFamilias;
    }

    public JList<String> getListaVeterinarios() {
        return listaVeterinarios;
    }

    public JList<String> getListaVoluntarios() {
        return listaVoluntarios;
    }

    
    


    public JButton getBtnAplicar() {
        return btnAplicar;
    }


    public JButton getBtnEliminarUsuario() {
        return btnEliminarUsuario;
    }

    public JButton getBtnReporte() {
        return btnReporte;
    }

    public JButton getBtnZonas() {
        return btnZonas;
    }

    public JComboBox<String> getComboTipoReporte() {
        return comboTipoReporte;
    }

    public JComboBox<Zona> getComboZona() {
        return comboZona;
    }
    
    
    

    
    
    

    
}
