/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.administrador;

import java.awt.Frame;
import java.util.List;
import javax.swing.DefaultListModel;
import modelo.Gato;

/**
 *
 * @author ms_ma
 */
public class VentanaReporte extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaReporte.class.getName());

    /**
     * Creates new form VentanaReporte
     */
    public VentanaReporte(Frame parent, boolean modal, 
                           List<Gato> datos, String tituloReporte) {
        super(parent, modal);
        initComponents();

        lblTitulo.setText(tituloReporte);

        DefaultListModel<String> model = new DefaultListModel<>();
        for (Gato g : datos) {
            model.addElement(g.toString());
        }
        listaGatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaGatos = new javax.swing.JList<>();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel2.setLayout(new java.awt.GridLayout());

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblTitulo);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportView(listaGatos);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnCerrar.setText("Cerrar");
        jPanel1.add(btnCerrar, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listaGatos;
    // End of variables declaration//GEN-END:variables
}
