/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.zona;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author ms_ma
 */
public class VentanaZona extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaZona.class.getName());
    
    public VentanaZona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelReportes = new javax.swing.JPanel();
        panelGatos = new javax.swing.JPanel();
        panelReportesCentro = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaZonas = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        panelAgregar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextPane();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(75, 100, 75, 100));
        panel.setMinimumSize(new java.awt.Dimension(600, 400));
        panel.setPreferredSize(new java.awt.Dimension(600, 400));
        panel.setLayout(new java.awt.BorderLayout());

        panelTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 30, 30, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zonas");
        panelTitulo.add(jLabel1);

        panel.add(panelTitulo, java.awt.BorderLayout.NORTH);

        panelReportes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        panelReportes.setLayout(new java.awt.GridBagLayout());

        panelGatos.setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        panelReportesCentro.setLayout(new java.awt.BorderLayout(0, 15));

        jScrollPane4.setViewportView(listaZonas);

        panelReportesCentro.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout());

        btnEliminar.setText("Eliminar Zona");
        jPanel1.add(btnEliminar);

        panelReportesCentro.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panelGatos.add(panelReportesCentro);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelReportes.add(panelGatos, gridBagConstraints);

        panelAgregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        panelAgregar.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jScrollPane1.setViewportView(txtNombre);

        panelAgregar.add(jScrollPane1);

        btnAgregar.setText("Agregar Zona");
        panelAgregar.add(btnAgregar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        panelReportes.add(panelAgregar, gridBagConstraints);

        panel.add(panelReportes, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaZona dialog = new VentanaZona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaZonas;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JPanel panelGatos;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel panelReportesCentro;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextPane txtNombre;
    // End of variables declaration//GEN-END:variables


    
    
    public void cargarListaZonas(List<String> items) {
        DefaultListModel<String> m = new DefaultListModel<>();
        items.forEach(m::addElement);
        listaZonas.setModel(m);
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JTextPane getTxtNombre() {
        return txtNombre;
    }

    public JList<String> getListaZonas() {
        return listaZonas;
    }

    
}
